name: Build Release APK

on:
  workflow_dispatch:


jobs:
  build-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant Execute Permission
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew :androidApp:assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: androidApp/build/outputs/apk/release/*.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: release-${{ github.run_number }}
          name: Release #${{ github.run_number }}
          files: androidApp/build/outputs/apk/release/*.apk